In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
print(np.__version__)

1.24.3

In [3]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [7]:
dataset=dataset.astype(int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [8]:
dataset["classification_yes"].value_counts()
#The value_counts method in Pandas is used to obtain a series containing counts of unique values in a column.

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [10]:
indep=dataset[["age", "bp", "al", "su", "bgr", "bu", "sc", "sod","pot", "hrmo", "pcv",
       "wc", "rc", "sg_b", "sg_c", "sg_d", "sg_e", "rbc_normal", "pc_normal",
       "pcc_present", "ba_present", "htn_yes", "dm_yes", "cad_yes",
       "appet_yes", "pe_yes", "ane_yes"]]
dep=dataset["classification_yes"]

In [11]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [15]:
from sklearn.model_selection import GridSearchCV

In [16]:
param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\lavanya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\lavanya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\lavanya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\lavanya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\lavanya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\lavanya\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.96965562 0.97899895 0.97515254 0.98515583
        nan        nan 0.96637037 0.98224963 0.98180577 0.98822372]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [17]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [18]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003003,0.006006,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000000,0.000000,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.072794,0.026353,0.009688,0.006454,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.985075,0.971429,0.952381,0.969697,0.969697,0.969656,0.010386,7
3,0.323951,0.008065,0.030413,0.005083,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.970588,0.985507,0.968750,0.985075,0.985075,0.978999,0.007642,5
4,0.041646,0.006461,0.003905,0.005646,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.985075,0.985507,0.935484,0.969697,1.000000,0.975153,0.022029,6
5,0.301073,0.023096,0.028045,0.006231,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.985507,0.985507,0.984615,0.985075,0.985075,0.985156,0.000332,2
6,0.000000,0.000000,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.003330,0.006166,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.035642,0.009845,0.009197,0.006162,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.985075,0.956522,0.935484,0.969697,0.985075,0.966370,0.018771,8
9,0.341501,0.040209,0.028160,0.012226,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.985507,0.971429,0.984615,0.969697,1.000000,0.982250,0.011009,3
10,0.032631,0.008492,0.009842,0.005506,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.969697,0.985507,0.968750,0.985075,1.000000,0.981806,0.011597,4
11,0.366454,0.041308,0.022286,0.008260,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.971429,0.984615,0.985075,1.000000,0.988224,0.010792,1

In [21]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9924946382275899

In [22]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [23]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [24]:
table_pr=pd.DataFrame()

In [25]:
print(X_test)

     age   bp  al  su  bgr  bu  sc  sod  pot  hrmo  ...  rbc_normal  \
132   46   70   0   0  100  47   0  142    3    16  ...           1
309   66   90   2   0  153  76   3  137    4    12  ...           1
334   69   70   0   0   83  42   1  139    3    16  ...           1
196   55  100   1   4  297  53   2  139    4    11  ...           1
246   60   90   2   0  105  53   2  136    5    11  ...           0
..   ...  ...  ..  ..  ...  ..  ..  ...  ...   ...  ...         ...
349   71   70   0   0   81  18   0  145    5    14  ...           1
168   50   80   0   0  137  46   0  139    5    14  ...           1
150   48  100   0   0  103  79   5  135    6     6  ...           1
392   51   60   3   0  148  34   1  137    4    10  ...           0
66    34   60   0   0   91  49   1  135    4    13  ...           1

     pc_normal  pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  \
132          1            0           0        0       0        0          1
309          1            0           1        0       0        0          0
334          1            0           0        0       0        0          1
196          1            0           0        1       1        0          1
246          1            0           0        0       0        0          1
..         ...          ...         ...      ...     ...      ...        ...
349          1            0           0        0       0        0          1
168          1            0           0        0       0        0          1
150          1            0           0        1       0        1          0
392          0            0           0        0       0        0          1
66           1            0           0        0       0        0          1

     pe_yes  ane_yes
132       0        0
309       0        0
334       0        0
196       0        0
246       0        0
..      ...      ...
349       0        0
168       0        0
150       0        0
392       0        0
66        0        0

[133 rows x 27 columns]

In [26]:
age_input=float(input("age:"))
bp_input=float(input("bp:"))
al_input=float(input("al:"))
su_input=float(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=float(input("pcv:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=float(input("sg_b(1/0):"))
sg_c_input=float(input("sg_c(1/0):"))
sg_d_input=float(input("sg_d(1/0):"))
sg_e_input=float(input("sg_e(1/0):"))
rbc_normal_input=float(input("rbc(1/0):"))
pc_normal_input=float(input("pc(1/0):"))
pcc_present_input=float(input("pcc(1/0):"))
ba_present_input=float(input("ba(1/0):"))
htn_yes_input=float(input("htn(1/0):"))
dm_yes_input=float(input("dm(1/0):"))
cad_yes_input=float(input("cad(1/0):"))
appet_yes_input=float(input("appet(1/0):"))
pe_yes_input=float(input("pe(1/0):"))
ane_yes_input=float(input("ane(1/0):"))

age:40
bp:80
al:0
su:0
bgr:140
bu:10
sc:1.2
sod:135
pot:5
hrmo:15
pcv:48
wc:10400
rc:4.5
sg_b(1/0):1
sg_c(1/0):0
sg_d(1/0):0
sg_e(1/0):0
rbc(1/0):1
pc(1/0):1
pcc(1/0):0
ba(1/0):0
htn(1/0):0
dm(1/0):0
cad(1/0):0
appet(1/0):1
pe(1/0):0
ane(1/0):0

In [27]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input
,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input
,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]